# Generated by Django 2.1.4 on 2019-01-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqueronteApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='fecha_c',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_c',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
