# Generated by Django 2.1.4 on 2019-01-14 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aqueronteApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='id_sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aqueronteApp.Tokens'),
        ),
        migrations.AlterUniqueTogether(
            name='usuarios',
            unique_together={('pers_id', 'id_sesion')},
        ),
    ]
