# Generated by Django 2.1.4 on 2019-01-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqueronteApp', '0002_auto_20190114_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='fecha_m',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
